defmodule Hawk.PhoenixAuth do
  @moduledoc """
  Integration helpers for Phoenix apps generated with `phx.gen.auth`.

  Phoenix authentication remains application-owned. Hawk only provides the glue
  that turns a generated `current_scope` into `Hawk.Authority` and assigns it in
  the places Hawk's JSON:API controllers and LiveViews already read.
  """

  alias Hawk.Authority

  @authority_assign :authority
  @hawk_authority_assign :hawk_authority
  @scope_assign :current_scope

  @doc """
  Plug-style callback that assigns Hawk authority from an existing current scope
  or from a bearer token.

  Options:

    * `:authority` - required resolver as function or `{module, function}`. It
      receives the current scope and returns a `Hawk.Authority`.
    * `:scope_assign` - generated auth assign key, defaults to `:current_scope`.
    * `:bearer` - optional bearer config. See `fetch_bearer_scope/2`.
  """
  def init(opts), do: opts

  def call(conn, opts) do
    scope_assign = Keyword.get(opts, :scope_assign, @scope_assign)
    scope = current_scope(conn, scope_assign) || fetch_bearer_scope(conn, Keyword.get(opts, :bearer, []))
    authority = current_authority(conn) || resolve_authority(scope, opts)

    conn
    |> assign_if_present(scope_assign, scope)
    |> assign_value(@hawk_authority_assign, authority)
    |> assign_value(@authority_assign, authority)
  end

  @doc """
  LiveView `on_mount` callback that converts `socket.assigns.current_scope` to
  Hawk authority.

  Use after the generated `UserAuth` on_mount has assigned `current_scope`.
  """
  def on_mount({:mount_current_authority, opts}, _params, _session, socket) do
    scope_assign = Keyword.get(opts, :scope_assign, @scope_assign)
    scope = current_scope(socket, scope_assign)
    authority = resolve_authority(scope, opts)

    {:cont,
     socket
     |> assign_value(@hawk_authority_assign, authority)
     |> assign_value(@authority_assign, authority)}
  end

  @doc """
  Converts a `phx.gen.auth` scope to a Hawk authority using declarative paths.
  """
  def authority_from_scope(scope, opts) do
    user = get_in_path(scope, Keyword.get(opts, :user_path, [:user]))

    cond do
      is_nil(user) ->
        Authority.public()

      role = role_from_user(user, opts) ->
        identity = get_in_path(user, Keyword.get(opts, :identity_path, [:id]))
        scopes = scopes_from_user(user, Keyword.get(opts, :scopes, []))

        if role == :system do
          Authority.system(identity: identity, scopes: scopes)
        else
          Authority.new(role, identity, scopes: scopes)
        end
    end
  end

  @doc """
  Fetches a phx.gen.auth scope from a Bearer token.

  `:bearer` options:

    * `:accounts` - context module generated by phx.gen.auth.
    * `:verify` - verifier function name, defaults to `:get_user_by_session_token`.
    * `:scope` - scope module with `for_user/1`.
  """
  def fetch_bearer_scope(_conn, []), do: nil

  def fetch_bearer_scope(conn, opts) do
    with token when is_binary(token) <- bearer_token(conn),
         token = decode_bearer_token(token),
         accounts when is_atom(accounts) <- Keyword.get(opts, :accounts),
         scope_module when is_atom(scope_module) <- Keyword.get(opts, :scope),
         {user, _token_record} <- apply(accounts, Keyword.get(opts, :verify, :get_user_by_session_token), [token]) do
      scope_module.for_user(user)
    else
      _missing_or_invalid -> nil
    end
  end

  defp decode_bearer_token(token) do
    case Base.url_decode64(token, padding: false) do
      {:ok, decoded} -> decoded
      :error -> token
    end
  end

  def bearer_token(conn) do
    conn
    |> header("authorization")
    |> case do
      "Bearer " <> token -> String.trim(token)
      "bearer " <> token -> String.trim(token)
      _other -> nil
    end
  end

  defp resolve_authority(scope, opts) do
    resolver = Keyword.get(opts, :authority) || raise ArgumentError, "Hawk.PhoenixAuth requires :authority"

    case call_resolver(resolver, scope) do
      %Authority{} = authority -> authority
      nil -> Authority.public()
    end
  end

  defp call_resolver(fun, scope) when is_function(fun, 1), do: fun.(scope)
  defp call_resolver({module, function}, scope), do: apply(module, function, [scope])
  defp call_resolver({module, function, extra_args}, scope), do: apply(module, function, [scope | extra_args])

  defp current_authority(source) do
    case fetch_assign(source, @authority_assign) do
      {:ok, %Authority{} = authority} -> authority
      _other -> nil
    end
  end

  defp current_scope(source, key) do
    case fetch_assign(source, key) do
      {:ok, value} -> value
      :error -> nil
    end
  end

  defp fetch_assign(%{assigns: assigns}, key) when is_map(assigns), do: Map.fetch(assigns, key)
  defp fetch_assign(%{} = map, key), do: Map.fetch(map, key)

  defp assign_if_present(source, _key, nil), do: source
  defp assign_if_present(source, key, value), do: assign_value(source, key, value)

  defp assign_value(%{assigns: assigns} = source, key, value) when is_map(assigns) do
    put_in(source.assigns, Map.put(assigns, key, value))
  end

  defp assign_value(%{} = source, key, value), do: Map.put(source, key, value)

  defp role_from_user(user, opts) do
    cond do
      resolver = Keyword.get(opts, :role) -> normalize_role(call_resolver(resolver, user))
      path = Keyword.get(opts, :role_path) -> normalize_role(get_in_path(user, path))
      true -> :user
    end
  end

  defp normalize_role(nil), do: nil
  defp normalize_role(role) when is_atom(role), do: role
  defp normalize_role(role) when is_binary(role), do: String.to_existing_atom(role)

  defp scopes_from_user(user, mappings) do
    Map.new(mappings, fn {scope_key, path} -> {scope_key, get_in_path(user, List.wrap(path))} end)
    |> Map.reject(fn {_key, value} -> is_nil(value) end)
  end

  defp get_in_path(nil, _path), do: nil

  defp get_in_path(source, path) do
    Enum.reduce(path, source, fn key, acc ->
      cond do
        is_nil(acc) -> nil
        is_map(acc) -> Map.get(acc, key) || Map.get(acc, to_string(key))
        true -> nil
      end
    end)
  end

  defp header(%{req_headers: headers}, name) when is_list(headers) do
    downcased_name = String.downcase(name)

    Enum.find_value(headers, fn {header, value} ->
      if String.downcase(to_string(header)) == downcased_name, do: value
    end)
  end

  defp header(_conn, _name), do: nil
end
